- name: File Watch Rulebook
  hosts: localhost
  sources:
    - name: file_watch
      ansible.eda.filesystem:
        path: /tmp/eda-watch/trigger.txt
        recursive: false

  rules:
    - name: on file change
      condition: event.type == "modified"
      action:
        run_playbook:
          name: playbooks/notify_on_file_change.yml
